// Remote Types
export const FETCHING_RANDOM_USERS_DATA = 'FETCHING_RANDOM_USERS_DATA';
export const FETCHING_RANDOM_USERS_DATA_SUCCESS = 'FETCHING_RANDOM_USERS_DATA_SUCCESS';
export const FETCHING_RANDOM_USERS_DATA_FAILURE = 'FETCHING_RANDOM_USERS_DATA_FAILURE';

// Game Types
export const CORRECT = 'CORRECT';
export const INCORRECT = 'INCORRECT';
export const RESET_GAME = 'RESET_GAME';